from ubuntu:16.04
MAINTAINER Tuhin Sharma "tuhinsharma121@gmail.com"

RUN apt-get update --fix-missing && \
    apt-get -y upgrade && \
    apt-get install -y python3-pip


RUN apt-get install -y build-essential cmake && \
    apt-get install -y libgtk-3-dev && \
    apt-get install -y libboost-all-dev

# --------------------------------------------------------------------------------------------------
# install python packages
# --------------------------------------------------------------------------------------------------
COPY ./requirements.txt /
RUN pip3 install --upgrade pip
RUN pip3 install -r /requirements.txt && rm /requirements.txt


# --------------------------------------------------------------------------------------------------
# copy src code and scripts into root dir /
# the crawler.py code assumes this dir structure
# --------------------------------------------------------------------------------------------------
COPY ./face_recognition_platform/deployment/app.py /app.py
COPY ./face_recognition_platform /face_recognition_platform
COPY ./face_recognition_platform/src /src
COPY ./faces /faces
COPY ./images /images
COPY ./models /models

# --------------------------------------------------------------------------------------------------
# add entrypoint for the container
# --------------------------------------------------------------------------------------------------
ADD ./face_recognition_platform/scripts/entrypoint.sh /bin/entrypoint.sh
RUN chmod +x /bin/entrypoint.sh
ENTRYPOINT ["/bin/entrypoint.sh"]
